state.*:
  type: config_entity
  label: 'States'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    form_parent:
      type: string
      label: 'States'
      translatable: true
    field_target:
      type: string
      label: 'If ajax behaviors'
    field_toggle:
      type: string
      label: 'If ajax behaviors'
    state_type_element:
      type: string
      label: 'If ajax behaviors'
    state_type:
      type: string
      label: 'If ajax behaviors'
    value_nested:
      type: string
      label: 'value nested'
